version: 2

project_name: smtfetch

before:
  hooks:
    - go mod tidy

builds:
  - id: smtfetch
    main: .
    binary: smtfetch

    goos:
      - windows
      - linux

    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: henristr
    name: smtfetch